- name: Checking for intel_pt support in cpuinfo
  ansible.builtin.command: |
    grep intel_pt /proc/cpuinfo
  register: res
  failed_when: res.rc != 0
  changed_when: false
  tags:
    - hardware_check

- name: Checking that pmu_name is not broadwell
  ansible.builtin.shell: |
    cat /sys/devices/cpu*/caps/pmu_name
  register: pmu_name
  changed_when: false
  tags:
    - hardware_check
  failed_when: pmu_name.stdout.find('broadwell') != -1
